FROM node:9.11

RUN mkdir -p /sbotify/src

WORKDIR /sbotify

ADD ./package.json /tmp/package.json
ADD ./yarn.lock /tmp/yarn.lock
RUN cd /tmp && yarn
RUN cp -a /tmp/node_modules ${WORKDIR}/

# Copy contents to the WORKDIR
COPY . ${WORKDIR}
RUN [ "npm", "run", "build" ]

EXPOSE 80
CMD [ "npm", "start" ]
